/* GENERATED by brand/tools/sync-brand-data.py from brand/tokens/themes.seed.json — do not edit. */
window.QISTAS_SEED = {
  "$schema": "qistas-themes/1",
  "_note": "Canonical seed for the theme engine. A theme stores only the tokens it CHANGES; dependent tokens (text-on-colour, hero gradient, dark-mode surfaces, accessible accent text, logo colours) are derived by the runtime unless pinned. After editing run: python brand/tools/sync-brand-data.py",
  "themes": [
    {
      "id": "base",
      "kind": "base",
      "name": {
        "en": "Qistas Signature",
        "ar": "قسطاس الأصيل"
      },
      "status": "published",
      "priority": 0,
      "publishedAt": "2026-10-07T00:00:00Z",
      "scope": {
        "countries": [
          "*"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {
        "tagline": {
          "en": "The just balance.",
          "ar": "الميزان العادل",
          "fr": "La juste balance.",
          "es": "La balanza justa.",
          "ur": "منصفانہ میزان"
        }
      },
      "tokens": {
        "light": {
          "primary": "#0B1F44",
          "onPrimary": "#F7F3EA",
          "action": "#0B1F44",
          "onAction": "#F7F3EA",
          "accent": "#C9A25B",
          "onAccent": "#0B1F44",
          "accentText": "#7F6126",
          "info": "#1C6BA4",
          "onInfo": "#FFFFFF",
          "bg": "#F7F3EA",
          "surface": "#FFFFFF",
          "surfaceAlt": "#EFE9DB",
          "ink": "#0B1F44",
          "inkMuted": "#4F5B76",
          "line": "#E3DCCB",
          "positive": "#1B7F5C",
          "warning": "#9A5700",
          "danger": "#B3261E",
          "tintSky": "#DDEDFA",
          "tintBlush": "#F6E4EA",
          "tintSand": "#F8EBCB",
          "tintMint": "#DCF2E8",
          "heroFrom": "#0B1F44",
          "heroTo": "#1B3A78",
          "logoInk": "#0B1F44",
          "logoAccent": "#C9A25B"
        },
        "dark": {
          "primary": "#163A7A",
          "onPrimary": "#F7F3EA",
          "action": "#C9A25B",
          "onAction": "#0B1F44",
          "accent": "#D4AE68",
          "onAccent": "#0B1F44",
          "accentText": "#DDBB7A",
          "info": "#6AAEE0",
          "onInfo": "#071634",
          "bg": "#071634",
          "surface": "#0E2250",
          "surfaceAlt": "#14295F",
          "ink": "#F2EEE3",
          "inkMuted": "#A9B4CC",
          "line": "#22386B",
          "positive": "#41C795",
          "warning": "#EBB04A",
          "danger": "#F28B82",
          "tintSky": "#14355F",
          "tintBlush": "#3A2540",
          "tintSand": "#3A3320",
          "tintMint": "#123B31",
          "heroFrom": "#1A4290",
          "heroTo": "#0E2A5C",
          "logoInk": "#F7F3EA",
          "logoAccent": "#D4AE68"
        }
      }
    },
    {
      "id": "country-sa",
      "kind": "country",
      "name": {
        "en": "Saudi Arabia — Red Sea Teal",
        "ar": "السعودية — فيروز البحر الأحمر"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:01Z",
      "scope": {
        "countries": [
          "SA"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {},
      "tokens": {
        "light": {
          "primary": "#0E3B43",
          "info": "#1B6F8F"
        },
        "dark": {}
      }
    },
    {
      "id": "country-ae",
      "kind": "country",
      "name": {
        "en": "United Arab Emirates — Gulf Dusk",
        "ar": "الإمارات — غسق الخليج"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:02Z",
      "scope": {
        "countries": [
          "AE"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {},
      "tokens": {
        "light": {
          "primary": "#1A1F4D",
          "accent": "#D2A06B",
          "info": "#3F5FC4"
        },
        "dark": {}
      }
    },
    {
      "id": "country-eg",
      "kind": "country",
      "name": {
        "en": "Egypt — Nile & Sand",
        "ar": "مصر — النيل والرمال"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:03Z",
      "scope": {
        "countries": [
          "EG"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {},
      "tokens": {
        "light": {
          "primary": "#14395B",
          "accent": "#D9A441",
          "info": "#1F6EA6"
        },
        "dark": {}
      }
    },
    {
      "id": "country-ma",
      "kind": "country",
      "name": {
        "en": "Morocco — Majorelle",
        "ar": "المغرب — ماجوريل"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:04Z",
      "scope": {
        "countries": [
          "MA"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {},
      "tokens": {
        "light": {
          "primary": "#1F2D7A",
          "accent": "#D98E32",
          "info": "#3558C8"
        },
        "dark": {}
      }
    },
    {
      "id": "country-pk",
      "kind": "country",
      "name": {
        "en": "Pakistan — Forest & Gold",
        "ar": "باكستان — الغابة والذهب"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:05Z",
      "scope": {
        "countries": [
          "PK"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {},
      "tokens": {
        "light": {
          "primary": "#0B3E2E",
          "info": "#1B6A8F"
        },
        "dark": {}
      }
    },
    {
      "id": "country-fr",
      "kind": "country",
      "name": {
        "en": "France — Encre",
        "ar": "فرنسا — الحبر"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:06Z",
      "scope": {
        "countries": [
          "FR"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {},
      "tokens": {
        "light": {
          "primary": "#1B2A49",
          "accent": "#B79A5F"
        },
        "dark": {}
      }
    },
    {
      "id": "country-es",
      "kind": "country",
      "name": {
        "en": "Spain — Rioja",
        "ar": "إسبانيا — ريوخا"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:07Z",
      "scope": {
        "countries": [
          "ES"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "always": true
      },
      "allowTenantAccent": true,
      "motifs": [],
      "copy": {},
      "tokens": {
        "light": {
          "primary": "#5E1B2B",
          "accent": "#D4A24E"
        },
        "dark": {}
      }
    },
    {
      "id": "event-ramadan",
      "kind": "event",
      "name": {
        "en": "Ramadan",
        "ar": "رمضان"
      },
      "status": "published",
      "priority": 10,
      "publishedAt": "2026-10-07T00:00:10Z",
      "scope": {
        "countries": [
          "SA",
          "AE",
          "EG",
          "MA",
          "PK"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "recurrence": {
          "type": "hijri_yearly",
          "month": 9,
          "day": 1,
          "spanDays": 30
        }
      },
      "allowTenantAccent": true,
      "motifs": [
        "crescent"
      ],
      "copy": {
        "greeting": {
          "en": "Ramadan Kareem",
          "ar": "رمضان كريم",
          "fr": "Ramadan Moubarak",
          "es": "Ramadán Mubarak",
          "ur": "رمضان کریم"
        }
      },
      "tokens": {
        "light": {
          "primary": "#1B1750",
          "accent": "#DDB254",
          "info": "#4650C7",
          "heroTo": "#3B2D86"
        },
        "dark": {}
      }
    },
    {
      "id": "event-eid-fitr",
      "kind": "event",
      "name": {
        "en": "Eid al-Fitr",
        "ar": "عيد الفطر"
      },
      "status": "published",
      "priority": 20,
      "publishedAt": "2026-10-07T00:00:11Z",
      "scope": {
        "countries": [
          "SA",
          "AE",
          "EG",
          "MA",
          "PK"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "recurrence": {
          "type": "hijri_yearly",
          "month": 10,
          "day": 1,
          "spanDays": 3
        }
      },
      "allowTenantAccent": true,
      "motifs": [
        "crescent",
        "sparkle"
      ],
      "copy": {
        "greeting": {
          "en": "Eid Mubarak",
          "ar": "عيد مبارك",
          "fr": "Aïd Moubarak",
          "es": "Eid Mubarak",
          "ur": "عید مبارک"
        }
      },
      "tokens": {
        "light": {
          "primary": "#0F4D3A",
          "accent": "#E0BE72",
          "info": "#1C7A66",
          "heroTo": "#1C7A5A"
        },
        "dark": {}
      }
    },
    {
      "id": "event-eid-adha",
      "kind": "event",
      "name": {
        "en": "Eid al-Adha",
        "ar": "عيد الأضحى"
      },
      "status": "published",
      "priority": 20,
      "publishedAt": "2026-10-07T00:00:12Z",
      "scope": {
        "countries": [
          "SA",
          "AE",
          "EG",
          "MA",
          "PK"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "recurrence": {
          "type": "hijri_yearly",
          "month": 12,
          "day": 10,
          "spanDays": 4
        }
      },
      "allowTenantAccent": true,
      "motifs": [
        "crescent",
        "sparkle"
      ],
      "copy": {
        "greeting": {
          "en": "Eid Mubarak",
          "ar": "عيد أضحى مبارك",
          "fr": "Aïd Moubarak",
          "es": "Eid Mubarak",
          "ur": "عید الاضحیٰ مبارک"
        }
      },
      "tokens": {
        "light": {
          "primary": "#12463A",
          "accent": "#D8B56A",
          "info": "#20708E",
          "heroTo": "#2A7A63"
        },
        "dark": {}
      }
    },
    {
      "id": "event-sa-national-day",
      "kind": "event",
      "name": {
        "en": "Saudi National Day (23 Sep)",
        "ar": "اليوم الوطني السعودي"
      },
      "status": "published",
      "priority": 30,
      "publishedAt": "2026-10-07T00:00:13Z",
      "scope": {
        "countries": [
          "SA"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "recurrence": {
          "type": "gregorian_yearly",
          "month": 9,
          "day": 22,
          "spanDays": 2
        }
      },
      "allowTenantAccent": false,
      "motifs": [
        "bars"
      ],
      "copy": {
        "greeting": {
          "en": "Happy National Day",
          "ar": "كل عام والوطن بخير",
          "fr": "Joyeuse fête nationale",
          "es": "Feliz Día Nacional",
          "ur": "قومی دن مبارک"
        }
      },
      "tokens": {
        "light": {
          "primary": "#0A5C36",
          "accent": "#E3C77F",
          "info": "#1B7A57",
          "heroTo": "#14804F"
        },
        "dark": {}
      }
    },
    {
      "id": "event-ae-national-day",
      "kind": "event",
      "name": {
        "en": "UAE National Day (2 Dec)",
        "ar": "اليوم الوطني الإماراتي"
      },
      "status": "published",
      "priority": 30,
      "publishedAt": "2026-10-07T00:00:14Z",
      "scope": {
        "countries": [
          "AE"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "recurrence": {
          "type": "gregorian_yearly",
          "month": 12,
          "day": 1,
          "spanDays": 3
        }
      },
      "allowTenantAccent": false,
      "motifs": [
        "bars"
      ],
      "copy": {
        "greeting": {
          "en": "Happy National Day",
          "ar": "عيد الاتحاد المجيد",
          "fr": "Joyeuse fête nationale",
          "es": "Feliz Día Nacional",
          "ur": "قومی دن مبارک"
        }
      },
      "tokens": {
        "light": {
          "primary": "#101D33",
          "accent": "#C8102E",
          "info": "#1C6BA4",
          "heroTo": "#2A3B5C"
        },
        "dark": {}
      }
    },
    {
      "id": "event-pk-independence",
      "kind": "event",
      "name": {
        "en": "Pakistan Independence Day (14 Aug)",
        "ar": "عيد استقلال باكستان"
      },
      "status": "published",
      "priority": 30,
      "publishedAt": "2026-10-07T00:00:15Z",
      "scope": {
        "countries": [
          "PK"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "recurrence": {
          "type": "gregorian_yearly",
          "month": 8,
          "day": 13,
          "spanDays": 2
        }
      },
      "allowTenantAccent": false,
      "motifs": [
        "crescent"
      ],
      "copy": {
        "greeting": {
          "en": "Happy Independence Day",
          "ar": "عيد استقلال سعيد",
          "fr": "Bonne fête de l'indépendance",
          "es": "Feliz Día de la Independencia",
          "ur": "یومِ آزادی مبارک"
        }
      },
      "tokens": {
        "light": {
          "primary": "#01411C",
          "accent": "#C9A25B",
          "info": "#1B6A8F",
          "heroTo": "#0F6A38"
        },
        "dark": {}
      }
    },
    {
      "id": "event-new-year",
      "kind": "event",
      "name": {
        "en": "New Year",
        "ar": "رأس السنة"
      },
      "status": "published",
      "priority": 5,
      "publishedAt": "2026-10-07T00:00:16Z",
      "scope": {
        "countries": [
          "*"
        ],
        "plans": [
          "*"
        ],
        "tenants": [
          "*"
        ]
      },
      "schedule": {
        "recurrence": {
          "type": "gregorian_yearly",
          "month": 12,
          "day": 29,
          "spanDays": 5
        }
      },
      "allowTenantAccent": true,
      "motifs": [
        "sparkle"
      ],
      "copy": {
        "greeting": {
          "en": "Happy New Year",
          "ar": "سنة جديدة سعيدة",
          "fr": "Bonne année",
          "es": "Feliz año nuevo",
          "ur": "نیا سال مبارک"
        }
      },
      "tokens": {
        "light": {
          "primary": "#0A1630",
          "accent": "#E3C57A",
          "heroTo": "#23366B"
        },
        "dark": {}
      }
    }
  ]
};
