#!/usr/bin/env python3
"""
Generate everything that is derived from the two sources of truth:

  brand/tokens/themes.seed.json   (country / event / base themes)
  brand/tools/build_logo.py       (logo geometry)

Outputs
  brand/theme-studio/theme-data.js   window.QISTAS_SEED  (browser, works from file:// and http://)
  supabase/seed/theme_seed.sql       idempotent seed for the `themes` table
  brand/shared/qistas-logo.js        window.QistasLogo  (inline SVG logos that follow the live theme)

Run after editing the seed or the logo:   python brand/tools/sync-brand-data.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import build_logo as BL  # noqa: E402


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote", os.path.relpath(path, ROOT))


# ------------------------------------------------------------------ themes -> JS + SQL
seed_path = os.path.join(ROOT, "brand", "tokens", "themes.seed.json")
seed = json.load(open(seed_path, encoding="utf-8"))

write(os.path.join(ROOT, "brand", "theme-studio", "theme-data.js"),
      "/* GENERATED by brand/tools/sync-brand-data.py from brand/tokens/themes.seed.json — do not edit. */\n"
      "window.QISTAS_SEED = " + json.dumps(seed, ensure_ascii=False, indent=2) + ";\n")


def sql_text_array(items):
    return "ARRAY[" + ", ".join("'" + str(i).replace("'", "''") + "'" for i in items) + "]::text[]"


def sql_json(obj):
    return "$j$" + json.dumps(obj, ensure_ascii=False) + "$j$::jsonb"


rows = []
for t in seed["themes"]:
    sc, sch = t.get("scope", {}), t.get("schedule", {})
    rec = sch.get("recurrence")
    rows.append(
        "  ({slug}, '{kind}', {name}, '{status}', {prio}, {cc}, {pl}, {tn}, {st}, {en}, {rec}, {ata}, {tok}, {cop}, {mot}, {pub})".format(
            slug="'" + t["id"] + "'",
            kind=t["kind"],
            name=sql_json(t["name"]),
            status=t["status"],
            prio=t.get("priority", 0),
            cc=sql_text_array(sc.get("countries", ["*"])),
            pl=sql_text_array(sc.get("plans", ["*"])),
            tn=sql_text_array(sc.get("tenants", ["*"])),
            st=("'" + sch["startsAt"] + "'::timestamptz") if sch.get("startsAt") else "null",
            en=("'" + sch["endsAt"] + "'::timestamptz") if sch.get("endsAt") else "null",
            rec=sql_json(rec) if rec else "null",
            ata="true" if t.get("allowTenantAccent", True) else "false",
            tok=sql_json(t["tokens"]),
            cop=sql_json(t.get("copy", {})),
            mot=sql_text_array(t.get("motifs", [])),
            pub=("'" + t["publishedAt"] + "'::timestamptz") if t.get("publishedAt") else "null",
        ))

seed_sql = """-- GENERATED by brand/tools/sync-brand-data.py from brand/tokens/themes.seed.json — do not edit.
-- Idempotent: safe to run repeatedly. Requires migration 20261007000100_theme_engine.sql.
begin;

insert into public.themes
  (slug, kind, name, status, priority, scope_countries, scope_plans, scope_tenants,
   starts_at, ends_at, recurrence, allow_tenant_accent, tokens, copy, motifs, published_at)
values
{rows}
on conflict (slug) do update set
  kind = excluded.kind,
  name = excluded.name,
  status = excluded.status,
  priority = excluded.priority,
  scope_countries = excluded.scope_countries,
  scope_plans = excluded.scope_plans,
  scope_tenants = excluded.scope_tenants,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  recurrence = excluded.recurrence,
  allow_tenant_accent = excluded.allow_tenant_accent,
  tokens = excluded.tokens,
  copy = excluded.copy,
  motifs = excluded.motifs,
  published_at = excluded.published_at;

commit;
""".format(rows=",\n".join(rows))
write(os.path.join(ROOT, "supabase", "seed", "theme_seed.sql"), seed_sql)

# ------------------------------------------------------------------ logo -> JS
lat, ara = BL.latin_wordmark(), BL.arabic_wordmark()
reg = BL.symbol()
small = BL.symbol(t=34, bob_r=28, drop=34, gap=6)


def vb(mark, pad):
    x, y, w, h = BL.tight(mark, pad)
    return [round(x, 2), round(y, 2), round(w, 2), round(h, 2)]


logo = {
    "geom": lat["geom"],
    "latin": {
        "viewBox": vb(lat, 12), "width": round(lat["width"], 2),
        "ink": "".join(lat["ink"]), "gold": "".join(lat["gold"]),
        "letters": [{"name": L["name"], "ink": "".join(L["ink"]), "gold": "".join(L["gold"])} for L in lat["letters"]],
    },
    "arabic": {
        "viewBox": vb(ara, 12), "width": round(ara["width"], 2), "bbox": [round(v, 2) for v in ara["bbox"]],
        "ink": "".join(ara["ink"]), "gold": "".join(ara["gold"]),
        "dots": [{"cx": d["cx"], "cy": d["cy"], "r": 9.5} for d in json.load(open(os.path.join(HERE, "arabic-wordmark.json"), encoding="utf-8"))["dots"]],
    },
    "symbol": {"viewBox": vb(reg, 10), "ink": "".join(reg["ink"]), "gold": "".join(reg["gold"])},
    "symbolSmall": {"viewBox": vb(small, 10), "ink": "".join(small["ink"]), "gold": "".join(small["gold"])},
}

logo_js = """/* GENERATED by brand/tools/sync-brand-data.py from brand/tools/build_logo.py — do not edit.
 * Inline Qistas logos. Colours follow the live theme (--q-logo-ink / --q-logo-accent) so a seasonal
 * or country theme can recolour the logo, within the contrast guard-rails enforced by the theme engine.
 */
(function (root) {
  'use strict';
  var D = %s;
  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;'})[c]; }); }
  /** kind: wordmark | arabic | symbol | symbolSmall.  opts: { title, className, ink, accent, height, width } */
  function svg(kind, opts) {
    opts = opts || {};
    var key = kind === 'wordmark' ? 'latin' : kind === 'arabic' ? 'arabic' : kind;
    var m = D[key];
    if (!m) throw new Error('Unknown logo kind: ' + kind);
    var ink = opts.ink ? ' style="fill:' + opts.ink + '"' : '';
    var acc = opts.accent ? ' style="fill:' + opts.accent + '"' : '';
    var size = (opts.height ? ' height="' + opts.height + '"' : '') + (opts.width ? ' width="' + opts.width + '"' : '');
    return '<svg class="q-logo ' + esc(opts.className || '') + '" xmlns="http://www.w3.org/2000/svg" viewBox="' + m.viewBox.join(' ') + '"' + size +
      ' role="img" aria-label="' + esc(opts.title || (kind === 'arabic' ? 'قسطاس' : 'Qistas')) + '">' +
      '<path class="ink"' + ink + ' d="' + m.ink + '"/>' + (m.gold ? '<path class="acc"' + acc + ' d="' + m.gold + '"/>' : '') + '</svg>';
  }
  root.QistasLogo = { data: D, svg: svg };
})(typeof self !== 'undefined' ? self : this);
""" % json.dumps(logo, ensure_ascii=False)
write(os.path.join(ROOT, "brand", "shared", "qistas-logo.js"), logo_js)
